version: '3'

services:
  postgresql:
    image: docker.io/postgres:latest
    environment:
      POSTGRES_USER: humuuu
      POSTGRES_PASSWORD: hmm
      POSTGRES_DB: sclassdev
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
    driver:  local